services:
  - type: web
    name: ikigai-career-builder-backend
    env: node
    region: oregon
    plan: free
    rootDir: ikigai-Backend
    buildCommand: |
      pwd
      ls -la
      npm install
      npm run build
      ls -la dist
    startCommand: |
      pwd
      ls -la
      node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://ikigai-career-builder.vercel.app
    healthCheckPath: /api/health
    autoDeploy: true 